-- ============================================================
-- Snowflake Tutorial Assignment Solution
-- Author: Sandeep
-- Tool: SnowSQL CLI
-- ============================================================

-- TASK 1: SnowSQL Login and Connection Context
SELECT 
    CURRENT_USER(),
    CURRENT_ROLE(),
    CURRENT_WAREHOUSE(),
    CURRENT_DATABASE(),
    CURRENT_SCHEMA();

-- TASK 2: Creation of Snowflake Objects & Basic Operations
CREATE WAREHOUSE IF NOT EXISTS DEMO_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE;

USE WAREHOUSE DEMO_WH;

CREATE DATABASE IF NOT EXISTS DEMO_DB;
USE DATABASE DEMO_DB;

CREATE SCHEMA IF NOT EXISTS DEMO_SCHEMA;
USE SCHEMA DEMO_SCHEMA;

CREATE STAGE IF NOT EXISTS DEMO_STAGE;

CREATE OR REPLACE TABLE EMPLOYEES (
    EMP_ID INT,
    EMP_NAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    SALARY NUMBER(10,2)
);

INSERT INTO EMPLOYEES VALUES 
    (101, 'Alice', 'Engineering', 85000.00),
    (102, 'Bob', 'Data Science', 90000.00),
    (103, 'Charlie', 'Marketing', 65000.00);

SELECT * FROM EMPLOYEES;
UPDATE EMPLOYEES SET SALARY = 95000.00 WHERE EMP_ID = 102;
DELETE FROM EMPLOYEES WHERE EMP_ID = 103;
SELECT * FROM EMPLOYEES;

-- TASK 3: Data Loading Using SnowSQL
PUT file://C:/Users/sandeep/OneDrive/Desktop/data.csv @DEMO_DB.DEMO_SCHEMA.DEMO_STAGE OVERWRITE=TRUE;

COPY INTO EMPLOYEES
FROM @DEMO_DB.DEMO_SCHEMA.DEMO_STAGE/data.csv.gz
FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER = ',' SKIP_HEADER = 0)
ON_ERROR = 'CONTINUE';

SELECT * FROM EMPLOYEES ORDER BY EMP_ID;

-- TASK 4: Snowflake Time Travel
SET START_TIME = CURRENT_TIMESTAMP();

UPDATE EMPLOYEES SET SALARY = 120000.00 WHERE EMP_ID = 107;
DELETE FROM EMPLOYEES WHERE EMP_ID = 113;

SELECT * FROM EMPLOYEES ORDER BY EMP_ID;
SELECT * FROM EMPLOYEES AT(TIMESTAMP => $START_TIME) ORDER BY EMP_ID;

-- TASK 5: Data Recovery Using Time Travel
DELETE FROM EMPLOYEES WHERE DEPARTMENT = 'Sales';
SELECT * FROM EMPLOYEES WHERE DEPARTMENT = 'Sales';

SELECT * FROM EMPLOYEES AT(OFFSET => -120) WHERE DEPARTMENT = 'Sales';

INSERT INTO EMPLOYEES
SELECT * FROM EMPLOYEES AT(OFFSET => -120) WHERE DEPARTMENT = 'Sales';

SELECT * FROM EMPLOYEES ORDER BY EMP_ID;